### ISSUE TITLE
Oh you do Threejs?

### ISSUE THREAD

**Issue by InvokerMaster** [lastch/Angular-5-Threejs-Turning-Fireball#6]
@lastch

**Comment by lastch** [comment]
hey @InvokerMaster , sure.

**Comment by InvokerMaster** [comment]
Oh Great 😄

**Comment by lastch** [comment]
why?

**Comment by InvokerMaster** [comment]
Because I don't. Why did you change the name?

**Comment by lastch** [comment]
previous name was not beautiful 😆

**Comment by lastch** [comment]
you live well?

**Comment by InvokerMaster** [comment]
It was good 😺 Yes. sure thing

**Comment by InvokerMaster** [comment]
20K double

**Comment by InvokerMaster** [comment]
And you?

**Comment by lastch** [comment]
not good, nowadays. however good to hear

**Comment by lastch** [comment]
no tasks, no accounts, etc

**Comment by InvokerMaster** [comment]
Why not good? That's not good 😞

**Comment by InvokerMaster** [comment]
Why no accounts?

**Comment by lastch** [comment]
😒 dirty condition
all suspended

**Comment by InvokerMaster** [comment]
Ooops! Yes. actually I don't have any as well 😞

**Comment by InvokerMaster** [comment]
What about @slardar?

**Comment by lastch** [comment]
no worries, it will be better soon.
how do you double 20K then?
He is well

**Comment by InvokerMaster** [comment]
outside clients

**Comment by lastch** [comment]
not sure though, where do you get jobs?

**Comment by InvokerMaster** [comment]
how slardar do? how much?

**Comment by lastch** [comment]
he is similar with me, all are not very good.

**Comment by InvokerMaster** [comment]
5K? 6, 7, 8, 9, 10?

**Comment by lastch** [comment]
5k

**Comment by InvokerMaster** [comment]
It's not bad ~

**Comment by InvokerMaster** [comment]
All were from Upwork of course

**Comment by InvokerMaster** [comment]
how is your max in your side group?

**Comment by InvokerMaster** [comment]
Do you do iOS or Android?

**Comment by lastch** [comment]
I don't know about phone.

**Comment by InvokerMaster** [comment]
Not good. getting 10 from iOS development now

**Comment by lastch** [comment]
getting 10K?

**Comment by InvokerMaster** [comment]
one time, got 15k. yes

**Comment by lastch** [comment]
oh i see,

**Comment by lastch** [comment]
so IOS

**Comment by InvokerMaster** [comment]
5K per week. ;)

**Comment by lastch** [comment]
is it difficult?

**Comment by InvokerMaster** [comment]
No. it's so easy.

**Comment by InvokerMaster** [comment]
Android as well for YOU

**Comment by InvokerMaster** [comment]
I am expert of Laravel & Vuee & Twilio

**Comment by InvokerMaster** [comment]
Currently running 5 projects and 4 of them are Laravel & Vue or Twilio

**Comment by lastch** [comment]
awesome,

**Comment by lastch** [comment]
you are encouraging me. i was going to give up.

**Comment by InvokerMaster** [comment]
And how many for you?

**Comment by InvokerMaster** [comment]
😛 Kidding?

**Comment by lastch** [comment]
👍 noo

**Comment by InvokerMaster** [comment]
how many?

**Comment by InvokerMaster** [comment]
and what part? Angular still?

**Comment by lastch** [comment]
of course Angular still, and Node. Only 2 at the moment

**Comment by InvokerMaster** [comment]
And how was your ill? sorry should have asked this first

**Comment by lastch** [comment]
you are asking me so fast, but no problem
i already knew who you are
I am good.

**Comment by lastch** [comment]
you are getting fat still?

**Comment by InvokerMaster** [comment]
Yes. 85 😥

**Comment by lastch** [comment]
oh less than gordal, i thought you are already over 100.
don't eat too much, PIG!!!

**Comment by InvokerMaster** [comment]
how much gordal?

**Comment by lastch** [comment]
89 😆

**Comment by InvokerMaster** [comment]
Oh great

**Comment by lastch** [comment]
your girl friend is well?

**Comment by InvokerMaster** [comment]
I don't have

**Comment by lastch** [comment]
👩 you kicked all
